### ISSUE TITLE
Helm chart versions & Git tags to remain same

### ISSUE THREAD

**Issue by yashwanth-l** [controlplaneio-fluxcd/charts#34]
As OCI cannot check if the version exists with `helm search repo oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator --versions`, we could like to have the ability to check for the tag exists with `git ls-remote --tags https://github.com/controlplaneio-fluxcd/charts`, which could mean the chart version also exists in the process of automating the installation of the operator. 

Hence the consistency of the Git Tags and the Helm chart versions would help in that regard

**Comment by stefanprodan** [comment]
To automate the upgrade of the operator you should be using Flux, see https://fluxcd.control-plane.io/operator/flux-bootstrap-migration/#automating-flux-operator-upgrades

**Comment by yashwanth-l** [comment]
Thanks @stefanprodan -- Would that be that Flux would be installed via Operator? Or does it mean that the initial installation is done via some kind of automation and then flux can take over it?

**Comment by yashwanth-l** [comment]
Ah, then yeah, initial is non-flux way and then hand it over to flux. Thanks, @stefanprodan 🥳 !!
